app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('nanda/',nanda,name='nanda'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('contact/',contact,name='contact'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1

from app3.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('task/',task,name='task'),
]

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def nanda(request):
    return render(request,'nanda.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def contact(request):
    return render(request,'contact.html')

app3/views.py
from django.shortcuts import render

# Create your views here.


def task(request):
    return render(request,'task.html')

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Sorry girls I am not interested</h1>
        <h2>I dont wants loose my Happiness and Peace</h2>
        <h1>Better luck next time</h1>
        <a href="{% url 'app1:nanda' %}"><h1>Go back to nanda to impress Him </h1></a>
    </center>
</body>
</html>

templates/nanda.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Nanda Is a Single and he is ready to Mingle</h1>
        <h1>If any one interested</h1>
        <a href="{% url 'app2:contact' %}"><h1>Click here</h1></a>
    </center>
</body>
</html>

templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Leave Ur Boy Bestiesssssssssss</h1>
            <h1></h1>
    </center>
</body>
</html>